### ISSUE TITLE
cannot open file 'data/teste.csv'

### ISSUE THREAD

**Issue by lincolnfrias** [walefmachado/interface-atuarial#33]
Ao executar global.R, surgiu o seguinte erro:

```
Warning in file(file, "rt") :
  cannot open file 'data/teste.csv': No such file or directory
Error in file(file, "rt") : cannot open the connection
```

Parece que tudo se resolveu apagando o seguinte comando:

```
teste <- read.delim('data/teste.csv',
                    stringsAsFactors = FALSE, header=TRUE)

```

**Comment by yagholc** [comment]
Obrigado pelo aviso!

Esse comando foi um remanescente de um teste que eu estava fazendo com a interface e esqueci de apagar,  no próximo commit eu corrijo.
